### ISSUE TITLE
Sigit module 'lxml' not installing

### ISSUE THREAD

**Issue by priyanshu-karmakar** [termuxhackers-id/SIGIT#10]
Termux sigit module 'lxml' not instaling ,all modules are installed bit lxml is not installing, it stops at a point and stops working 
![Screenshot_2021-05-03-09-
`34-14-74](https://user-images.githubusercontent.com/83566287/116840250-c2965700-abf2-11eb-91fb-6e5c641d2e4b.png)`

**Comment by termuxhackers-id** [comment]
> Termux sigit module 'lxml' not instaling ,all modules are installed bit lxml is not installing, it stops at a point and stops working

If stopped, install manual with:
$ pip3 install lxml

If stuck not stopped:
this could take a while, just wait for a minute
