### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by omgamer** [termuxhackers-id/SIGIT#11]
![Uploading Screenshot_20210503_155711.png…]()
 **Not only this on every. Every time i dod something 403 error**

**Comment by termuxhackers-id** [comment]
> Not only this on every. Every time i dod something 403 error

Sorry i cant see your screenshot, can you put the output here ?

**Comment by omgamer** [comment]
> > Not only this on every. Every time i dod something 403 error
> 
> Sorry i cant see your screenshot, can you put the output here ?

It's not the repo problem it's mine it's fixed now ty
