### ISSUE TITLE
Digit Not opening

### ISSUE THREAD

**Issue by Mush2005** [termuxhackers-id/SIGIT#13]
Traceback (most recent call last):
  File "/usr/local/bin/sigit", line 9, in <module>
    from googlesearch import search
ModuleNotFoundError: No module named 'googlesearch'

Plz help

**Comment by termuxhackers-id** [comment]
> Traceback (most recent call last):
> File "/usr/local/bin/sigit", line 9, in
> from googlesearch import search
> ModuleNotFoundError: No module named 'googlesearch'

pip3 install googlesearch-python
