### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by 5mirok5** [termuxhackers-id/SIGIT#15]
u0_a336@localhost  ~  sigit
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/sigit", line 10, in <module>
    from lxml.html import fromstring
ModuleNotFoundError: No module named 'lxml'

**Comment by termuxhackers-id** [comment]
> u0_a336@localhost ~ sigit
> Traceback (most recent call last):
> File "/data/data/com.termux/files/usr/bin/sigit", line 10, in
> from lxml.html import fromstring
> ModuleNotFoundError: No module named 'lxml'

Termux:
pkg install libxml2 python
python3 -m pip install lxml
