### ISSUE TITLE
getpass in FB code?

### ISSUE THREAD

**Issue by Pussyhole420** [termuxhackers-id/SIGIT#24]
Does this steal our passwords based on what I'm seeing in the code assuming we input the correct cookie information? Reported to Github so they can have a look themselves.

**Comment by Biggitybaked** [comment]
Fairly certain you're a fucking moron, moron. Exactly what part of the dudes code that you and your infinite knowledge has seen even remotely resembles code that could steal fb passwords? Huh, genius? And why in the fuck would you snitch even if it could (which it cant). You the fucking git hub police making sure we all stay within the ToS? Should put up your coding hat and get a cop hat you douche bag.
