### ISSUE TITLE
STOLEN CODE- EGALOSINT

### ISSUE THREAD

**Issue by ArkAngeL43** [termuxhackers-id/SIGIT#25]
Someone stole your code and i think you should probobly claim it is YOUR code even after i prooved them wrong here 

https://github.com/C0MPL3XDEV/E4GL30S1NT/issues

however everything is the exact same, they just stole YOUR code and changed the banner and name 

at the bottom of the report i called them out for stealing YOUR code i noted this 
```
the date is a few months after SIGIT's Release, the code is the EXACT same, the banner call is the EXACT same, the kaliinstal.sh is the EXACT same, the coding style is the EXACT same, the percentage of languages is the EXACT same.
```

**Comment by Nullpython3950** [comment]
Oh no

**Comment by Nullpython3950** [comment]
This is bad for termuxhackers-id

**Comment by termuxhackers-id** [comment]
Thanks for report, idk what to do let them change the code that I made and not add the creator's source
