### ISSUE TITLE
Any ideas?

### ISSUE THREAD

**Issue by Biggitybaked** [termuxhackers-id/SIGIT#26]
➜  ~ pip install email_validator
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting email_validator
  Downloading email_validator-1.1.3-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: idna>=2.0.0 in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from email_validator) (2.10)
Requirement already satisfied: dnspython>=1.15.0 in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from email_validator) (1.16.0)
Installing collected packages: email-validator
Successfully installed email-validator-1.1.3
➜  ~ sigit                                      Traceback (most recent call last):                File "/data/data/com.termux/files/usr/bin/sigit", line 8, in <module>
    from email_validator import validate_email, EmailNotValidError
ModuleNotFoundError: No module named 'email_validator'

**Comment by termuxhackers-id** [comment]
Use python 3
