### ISSUE TITLE
No module named 'googlesearch.googlesearch'

### ISSUE THREAD

**Issue by netrunnerz** [termuxhackers-id/SIGIT#27]
![Screenshot_20220327-114806_Termux](https://user-images.githubusercontent.com/74891016/160274119-8d206746-59fe-4093-9da3-6dc41b840a68.jpg)

**Comment by n1n8-net** [comment]
pip install google
pip install google-search
pip install google-cloud

Try plz

**Comment by Cjxxii** [comment]
> 

Thanks man this work
