### ISSUE TITLE
And I can't uninstall sigit now with the command given 

### ISSUE THREAD

**Issue by darksoul6-max** [termuxhackers-id/SIGIT#4]

**Comment by termuxhackers-id** [comment]
Cam i see? put your screenshot here

**Comment by Rishabh72520** [comment]
![Screenshot_20210426_165356.jpg](https://user-images.githubusercontent.com/73374940/116082273-d86ac000-a6b8-11eb-8d8f-fab6c5502160.jpg)

**Comment by termuxhackers-id** [comment]
Please wait, this process take a while 🙂

**Comment by Rishabh72520** [comment]
How much time ??

**Comment by Rishabh72520** [comment]
Please send me video of this tools tutorial.

🙏😊

**Comment by Rishabh72520** [comment]
I wait for an hour but it's not working...

**Comment by Rishabh72520** [comment]
![Screenshot_20210427_071617.jpg](https://user-images.githubusercontent.com/73374940/116172497-82cdfc00-a728-11eb-8529-0af27ad71075.jpg)

**Comment by sumit-buddy** [comment]
> I wait for an hour but it's not working...

Hi @Rishabh72520 i was facing the same issue. 
I tried this command : `STATIC_DEPS=true pip install lxml` and it worked for me.

**Comment by Rishabh72520** [comment]
I ll try...

**Comment by Rishabh72520** [comment]
@sumit-buddy not working
