### ISSUE TITLE
It's not installing

### ISSUE THREAD

**Issue by Venom-dell** [termuxhackers-id/SIGIT#7]
I used the command provided and it gave the following output.

Output-
$ wget https://raw.githubusercontent.com/termuxhackers-id/SIGIT/main/install.sh && bash install.sh
--2021-04-29 20:18:23--  https://raw.githubusercontent.com/termuxhackers-id/SIGIT/main/install.sh
Resolving raw.githubusercontent.com... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com|185.199.110.133|:443... failed: Connection timed out.
Connecting to raw.githubusercontent.com|185.199.108.133|:443... failed: Connection timed out.
Connecting to raw.githubusercontent.com|185.199.109.133|:443... failed: Connection timed out.
Connecting to raw.githubusercontent.com|185.199.111.133|:443... failed: Connection timed out.
Retrying.

--2021-04-29 20:20:28--  (try: 2)  https://raw.githubusercontent.com/termuxhackers-id/SIGIT/main/install.sh
Connecting to raw.githubusercontent.com|185.199.110.133|:443... failed: Connection timed out.
Connecting to raw.githubusercontent.com|185.199.108.133|:443... failed: Connection timed out.
Connecting to raw.githubusercontent.com|185.199.109.133|:443... failed: Connection timed out.
Connecting to raw.githubusercontent.com|185.199.111.133|:443...

It's saying connection timed out even though I have a stable and fast internet connection. Later I used the command in Google cloud shell it was installed successfully but I wasn't able to use it

**Comment by sumit-buddy** [comment]
@Venom-dell 
It is working perfectly fine for me sir.
I think you should try upgrading packages.

`~ $ wget https://raw.githubusercontent.com/termuxhackers-id/SIGIT/main/install.sh && bash install.sh
--2021-04-29 23:23:43--  https://raw.githubusercontent.com/termuxhackers-id/SIGIT/main/install.sh
Resolving raw.githubusercontent.com... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1036 (1.0K) [text/plain]
Saving to: ‘install.sh’

install.sh     100%   1.01K  --.-KB/s    in 0s

2021-04-29 23:23:44 (8.80 MB/s) - ‘install.sh’ saved [1036/1036]

> SIGIT - Simple information gathering toolkit
> prepare for installing dependencies ...`

**Comment by sumit-buddy** [comment]
@Venom-dell 
It is also working perfectly on Google Cloud Shell.

**Comment by Venom-dell** [comment]
> @Venom-dell 
> It is working perfectly fine for me sir.
> I think you should try upgrading packages.
> 
> ```
> ~ $ wget https://raw.githubusercontent.com/termuxhackers-id/SIGIT/main/install.sh && bash install.sh
> --2021-04-29 23:23:43--  https://raw.githubusercontent.com/termuxhackers-id/SIGIT/main/install.sh
> Resolving raw.githubusercontent.com... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
> Connecting to raw.githubusercontent.com|185.199.109.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 1036 (1.0K) [text/plain]
> Saving to: ‘install.sh’
> 
> install.sh     100%   1.01K  --.-KB/s    in 0s
> 
> 2021-04-29 23:23:44 (8.80 MB/s) - ‘install.sh’ saved [1036/1036]
> 
> > SIGIT - Simple information gathering toolkit
> > prepare for installing dependencies ...
> ```

Thanks. It's working now.

**Comment by Rishabh72520** [comment]
Still not working...

**Comment by sumit-buddy** [comment]
> Still not working...

Try this command to install lxml : `STATIC_DEPS=true pip install lxml`
